### ISSUE TITLE
运行直接报错

### ISSUE THREAD

**Issue by TML007** [halohily/DriverEpoch#1]
clang: error: no such file or directory: '/Users/LY/Desktop/DriverEpoch/DriverEpoch/PrefixHeader.pch'
clang: error: no input files

**Comment by guowilling** [comment]
'/Users/LY/Desktop/DriverEpoch/DriverEpoch/PrefixHeader.pch' 改成 'DriverEpoch/PrefixHeader.pch'
即可

**Comment by halohily** [comment]
这个是由于之前的pch文件预编译地址没有设置成通配地址，我的疏忽，已经更新，感谢！
