### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by TML007** [halohily/DriverEpoch#2]
NSDictionary *parameters = @{@"if": @"AddPlace",@"user_id":user_id, @"latitude": latitude, @"longitude": longitude, @"place_name": self.locationStr, @"place_address": self.locationDic.formattedAddress};    参数有空

**Comment by guowilling** [comment]
同问, self.locationStr 这个值为 nil.

**Comment by halohily** [comment]
通知方式触发这个接口调用时，那个值会有空的情况，刚刚已经更新。感谢！
